package main

import (
	"strings"
	"testing"

	"tux-to-any/internal/plan"
)

const patchFixture = `# svc_demo.pc — generated by tuxgo (dispatch-axis scenarios).
#
# HOW TO USE: review or delete entries you do not want.

service: svc_demo
# module: svc_demo   # defaults to the service name

endpoints:
  - scenarioRef: c_flag=F # kept lines 352-982 | reads: FML_A | writes: FML_B
    name: "GetMfNavHist" # deterministic — edit freely
    route: "/mf-nav-hist"   # deterministic — edit freely
  - scenarioRef: c_flag=H # kept lines 180-982 | reads: FML_C | writes: FML_D
    name: "ProcessFreedom" # ai-suggested — edit freely
    route: "/freedom"      # ai-suggested — edit freely

dbMethods:                     # deterministic — edit freely; params stay
                               # derived from the query binds
  q1: {name: GetDateDetails}   # deterministic — edit freely
  cur_hist: {name: GetHist, row: HistRow}   # deterministic — edit freely
  fn_lib:q2: {name: GetLib, row: LibRow}   # deterministic — edit freely

# trailing census comment that must survive
`

func TestEndpointBlocksFindsRefsAndMarkers(t *testing.T) {
	blocks := endpointBlocks(strings.Split(patchFixture, "\n"))
	if len(blocks) != 2 {
		t.Fatalf("blocks = %d, want 2", len(blocks))
	}
	if blocks[0].refKind != "scenarioRef" || blocks[0].refValue != "c_flag=F" {
		t.Errorf("block 0 ref = %s/%s", blocks[0].refKind, blocks[0].refValue)
	}
	if blocks[0].aiNamed {
		t.Error("block 0 should not be marked ai-suggested")
	}
	if !blocks[1].aiNamed {
		t.Error("block 1 should be marked ai-suggested")
	}
}

func TestPatchMappingYAMLEndpointsAndPins(t *testing.T) {
	m := &plan.Mapping{
		Service: "svc_demo",
		Endpoints: []plan.Endpoint{
			{ScenarioRef: "c_flag=F", Name: "GetMfNavHist"},
			{ScenarioRef: "c_flag=H", Name: "ProcessFreedom"},
		},
	}
	blocks := endpointBlocks(strings.Split(patchFixture, "\n"))
	// The join keys map yaml blocks back onto the loader's endpoints.
	if e, ok := endpointForRef(m, blocks[1]); !ok || e.Name != "ProcessFreedom" {
		t.Errorf("endpointForRef(block[1]) = %v, %v", e, ok)
	}
	suggestions := map[string]aiSuggestion{
		"scenarioRef:c_flag=F": {
			Name: "ProcessFreedomRequest", Route: "/freedom-request",
			Methods: map[string]methodPinSuggestion{
				"q1":       {Name: "GetFreedomDate", Row: "FreedomDate"},
				"cur_hist": {Name: "GetFreedomHist"},
			},
		},
	}
	out := patchMappingYAML(patchFixture, blocks, suggestions)

	// The named block's values and marker flip; census comment survives.
	if !strings.Contains(out, `name: "ProcessFreedomRequest" # ai-suggested — edit freely`) {
		t.Errorf("name line not patched:\n%s", out)
	}
	if !strings.Contains(out, `route: "/freedom-request" # ai-suggested — edit freely`) {
		t.Errorf("route line not patched:\n%s", out)
	}
	if !strings.Contains(out, "# kept lines 352-982 | reads: FML_A | writes: FML_B") {
		t.Error("census comment lost")
	}
	// The ai-suggested block (no suggestion) passes through untouched.
	if !strings.Contains(out, `name: "ProcessFreedom" # ai-suggested — edit freely`) {
		t.Error("ai-suggested block was modified without a suggestion")
	}
	// dbMethods: name+row replace, name-only gains row, fn-lib id untouched.
	if !strings.Contains(out, "q1: {name: GetFreedomDate, row: FreedomDate}   # ai-suggested — edit freely") {
		t.Errorf("q1 pin not patched:\n%s", out)
	}
	if !strings.Contains(out, "cur_hist: {name: GetFreedomHist, row: HistRow}   # ai-suggested — edit freely") {
		t.Errorf("cur_hist pin not patched (row must be kept):\n%s", out)
	}
	if !strings.Contains(out, "fn_lib:q2: {name: GetLib, row: LibRow}") {
		t.Error("unpinned fn-library pin was modified")
	}
	// Header, trailing comments, service lines survive byte-for-byte.
	if !strings.Contains(out, "# trailing census comment that must survive") {
		t.Error("trailing comment lost")
	}
	if !strings.Contains(out, "service: svc_demo") {
		t.Error("service line lost")
	}
}

func TestPatchMappingYAMLNoSuggestionsIsIdentity(t *testing.T) {
	blocks := endpointBlocks(strings.Split(patchFixture, "\n"))
	out := patchMappingYAML(patchFixture, blocks, map[string]aiSuggestion{})
	if out != patchFixture {
		t.Errorf("patch with no suggestions changed the file:\n%s", out)
	}
}

// TestEndpointBlocksScenarioFilter pins the 4th ref kind's block parsing:
// a quoted filter (spaces and quotes inside) round-trips to the endpoint's
// join key, so the ainames patch addresses it like any other ref.
func TestEndpointBlocksScenarioFilter(t *testing.T) {
	const raw = `service: svcs
endpoints:
  - scenarioFilter: "c_flag == 'F' || c_flag == 'I'"   # kept ... | reads: ...
    name: "GetBoth" # deterministic — edit freely
    route: "/both"  # deterministic — edit freely
  - scenarioRef: c_flag=H
    name: "Hist"
    route: "/hist"
`
	blocks := endpointBlocks(strings.Split(raw, "\n"))
	if len(blocks) != 2 {
		t.Fatalf("blocks = %d, want 2", len(blocks))
	}
	if blocks[0].refKind != "scenarioFilter" || blocks[0].refValue != "c_flag == 'F' || c_flag == 'I'" {
		t.Errorf("block 0 ref = %s/%q", blocks[0].refKind, blocks[0].refValue)
	}
	m := &plan.Mapping{
		Service:   "svcs",
		Endpoints: []plan.Endpoint{{ScenarioFilter: "c_flag == 'F' || c_flag == 'I'", Name: "GetBoth", Route: "/both"}},
	}
	if e, ok := endpointForRef(m, blocks[0]); !ok || e.Name != "GetBoth" {
		t.Errorf("endpointForRef(filter block) = %v, %v", e, ok)
	}
}
