// Package csdraft renders the discover -target cs mapping drafts (B1/B2):
// the flow IR's scenario slices (dispatch-axis entries) or API candidates
// (legacy shapes) → one editable cs mapping draft per entry file, with
// namespace/area/component placeholders (filled from the config defaults
// when set), per-endpoint action/route suggestions, requestFields/paramNames
// from the FML read targets, and dbMethods const-name pins — zero
// hand-written yaml for a new file's first pass. Every suggestion is
// advisory: the tool never invents endpoints, it proposes them.
//
// The drafts live here (not in cmd) so the TUX_CS_CORPUS smoke can run the
// full draft → load → plan → generate pipeline against the local-only
// corpus.
package csdraft

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"tux-to-any/internal/csplan"
	"tux-to-any/internal/flow"
	"tux-to-any/internal/ir"
)

// Options carries the draft-time config defaults (C1): the namespace/area
// the draft fills its placeholders from when set (empty keeps an editable
// TODO placeholder).
type Options struct {
	Namespace string
	Area      string
}

// Render produces the cs mapping draft for one entry file.
func Render(f *ir.File, tree *flow.Tree, src []byte, opts Options) string {
	entry := filepath.Base(f.Path)
	stem := strings.TrimSuffix(entry, filepath.Ext(entry))
	var sb strings.Builder
	fmt.Fprintf(&sb, "# %s.cs.mapping.yaml — generated by tuxconv discover -target cs.\n", stem)
	sb.WriteString("#\n")
	sb.WriteString("# HOW TO USE: names/routes below are suggested defaults — review them\n")
	sb.WriteString("# (or delete entries you do not want), set namespace/component for your\n")
	sb.WriteString("# real tree, then convertcs. An arm you omit stays logic-only.\n")
	sb.WriteString("\n")
	fmt.Fprintf(&sb, "source: %s\n", entry)
	ns := opts.Namespace
	if ns == "" {
		ns = "CHANGE_ME_ROOT_NAMESPACE"
	}
	fmt.Fprintf(&sb, "namespace: %s   # TODO set the root namespace\n", ns)
	if opts.Area != "" {
		fmt.Fprintf(&sb, "area: %s   # area under the root — edit freely\n", opts.Area)
	} else {
		sb.WriteString("# area:                                # TODO set the dotted area under the root (or delete)\n")
	}
	component := ComponentOf(stem)
	fmt.Fprintf(&sb, "component: %s   # class stem: <Component>Controller/Service/Repository/Queries/DTO — edit freely\n", component)
	sb.WriteString("apiVersion: \"1.0\"\n")
	sb.WriteString("# requestDTO: object                   # the shared request type the actions take\n")
	sb.WriteString("# validator:                           # optional validator tag (\"\" skips validation)\n")

	axis := tree.DispatchAxisFor(src)
	if axis != nil {
		sb.WriteString("\nendpoints:\n")
		writeScenarioEndpoints(&sb, tree, axis, component, stem)
	} else {
		writeCandidateEndpoints(&sb, f, tree, component, stem)
	}

	writeRequestFields(&sb, f)
	writeDBMethods(&sb, f)
	return sb.String()
}

// writeScenarioEndpoints emits one scenarioRef endpoint per qualifying
// scenario slice (the census rubric — request reads AND non-error response
// writes); the logic-only slices stay commented for user control.
func writeScenarioEndpoints(sb *strings.Builder, tree *flow.Tree, axis *flow.DispatchAxis, component, stem string) {
	scens := flow.Scenarios(tree, axis)
	routeStem := routeStemOf(stem)
	var logicOnly []*flow.Scenario
	for _, sc := range scens {
		if len(sc.Gets) == 0 || len(sc.Adds) == 0 {
			logicOnly = append(logicOnly, sc)
			continue
		}
		ext := sc.BodyExtent()
		fmt.Fprintf(sb, "  - scenarioRef: %-16s # kept lines %d-%d | reads: %s | writes: %s\n",
			strconvQuote(sc.Key), ext[0], ext[1],
			capList(sc.Gets, 8), capList(sc.Adds, 8))
		fmt.Fprintf(sb, "    name: %-16s # deterministic — edit freely\n", strconvQuote(component+sc.Value))
		fmt.Fprintf(sb, "    route: %-16s # deterministic — edit freely\n", strconvQuote(routeStem+"_"+sc.Value))
	}
	if len(logicOnly) > 0 {
		sb.WriteString("# scenarios without reads+writes (the census rubric) — map manually if you know better:\n")
		for _, sc := range logicOnly {
			fmt.Fprintf(sb, "# - scenarioRef: %-14s # reads: %s | writes: %s\n",
				strconvQuote(sc.Key), capList(sc.Gets, 8), capList(sc.Adds, 8))
		}
	}
}

// writeCandidateEndpoints emits the non-axis fallback draft (legacy file
// shapes): one condition/conditionRef endpoint per API candidate.
func writeCandidateEndpoints(sb *strings.Builder, f *ir.File, tree *flow.Tree, component, stem string) {
	candidates := flow.Discover(tree, f.Conditions)
	if len(candidates) == 0 {
		fmt.Fprintf(sb, "\n# no API candidates found (%d conditions inspected, no dispatch axis) — map manually if you know better\n",
			len(f.Conditions))
		return
	}
	routeStem := routeStemOf(stem)
	sb.WriteString("\nendpoints:\n")
	for i, c := range candidates {
		ref := strconvQuote(c.Key)
		if strings.Contains(c.Key, ".") {
			fmt.Fprintf(sb, "  - conditionRef: %-12s # nested block, lines %d-%d | reads: %s | writes: %s\n",
				ref, c.StartLine, c.EndLine, capList(c.Gets, 8), capList(c.Adds, 8))
		} else {
			fmt.Fprintf(sb, "  - condition: %-15s # lines %d-%d | reads: %s | writes: %s\n",
				strings.TrimPrefix(c.Key, "c"), c.StartLine, c.EndLine, capList(c.Gets, 8), capList(c.Adds, 8))
		}
		n := i + 1
		fmt.Fprintf(sb, "    name: %-16s # deterministic — edit freely\n", strconvQuote(fmt.Sprintf("%sAction%d", component, n)))
		fmt.Fprintf(sb, "    route: %-16s # deterministic — edit freely\n", strconvQuote(fmt.Sprintf("%s_action%d", routeStem, n)))
	}
}

// writeRequestFields drafts requestFields/paramNames from the FML read
// targets (B2): every Fget32 target that is a typed host var — the vars
// that reach the repo signatures as named Oracle parameters. Values are
// the exact names the plan derives when the mapping leaves them unset.
func writeRequestFields(sb *strings.Builder, f *ir.File) {
	typed := map[string]bool{}
	for _, hv := range f.HostVars {
		if hv.CType != "" {
			typed[hv.Name] = true
		}
	}
	seen := map[string]bool{}
	var targets []string
	for _, op := range f.FmlOps {
		if op.Kind != ir.FmlGet || op.Target == "" || !typed[op.Target] || seen[op.Target] {
			continue
		}
		seen[op.Target] = true
		targets = append(targets, op.Target)
	}
	if len(targets) == 0 {
		return
	}
	sort.Strings(targets)
	sb.WriteString("\nrequestFields:                       # bind host var → request property — edit freely\n")
	for _, t := range targets {
		fmt.Fprintf(sb, "  %s: %s\n", t, csplan.SuggestRequestProp(t))
	}
	sb.WriteString("\nparamNames:                          # bind host var → named Oracle parameter — edit freely\n")
	for _, t := range targets {
		fmt.Fprintf(sb, "  %s: %s\n", t, csplan.SuggestRequestProp(t))
	}
}

// writeDBMethods pins every unique query's NamedQueries const name (B2):
// the exact names the plan derives when the mapping leaves them unset —
// the draft's pins and the plan's fallback cannot drift.
func writeDBMethods(sb *strings.Builder, f *ir.File) {
	var queries []*ir.Query
	for _, q := range f.Queries {
		if q.DuplicateOf == "" {
			queries = append(queries, q)
		}
	}
	if len(queries) == 0 {
		return
	}
	sb.WriteString("\ndbMethods:                           # query unit → NamedQueries const name — deterministic — edit freely\n")
	for _, q := range queries {
		fmt.Fprintf(sb, "  %s: {name: %s}\n", q.ID, csplan.DefaultQueryName(q, isDML(q)))
	}
}

func isDML(q *ir.Query) bool {
	switch q.Type {
	case ir.QueryInsert, ir.QueryUpdate, ir.QueryDelete, ir.QueryMerge:
		return true
	}
	return false
}

// ComponentOf derives the class stem from the entry name: the SVC_ prefix
// dropped, snake segments Pascal-joined (SVC_CUST_GET_DTL → CustGetDtl).
func ComponentOf(stem string) string {
	s := strings.TrimPrefix(stem, "SVC_")
	parts := strings.Split(s, "_")
	var sb strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		sb.WriteString(strings.ToUpper(part[:1]))
		sb.WriteString(strings.ToLower(part[1:]))
	}
	out := sb.String()
	if out == "" {
		return "Component"
	}
	return out
}

// routeStemOf renders the route prefix: the stem minus the SVC_ prefix,
// lowercased with underscores kept (CUST_GET_DTL → cust_get_dtl).
func routeStemOf(stem string) string {
	return strings.ToLower(strings.TrimPrefix(stem, "SVC_"))
}

// capList renders a census list compactly: the first cap entries, then
// "+N more" (the full census lives in the scenario artifacts).
func capList(fields []string, cap int) string {
	if len(fields) == 0 {
		return "none"
	}
	sorted := append([]string(nil), fields...)
	sort.Strings(sorted)
	if len(sorted) <= cap {
		return strings.Join(sorted, ",")
	}
	return strings.Join(sorted[:cap], ",") + fmt.Sprintf(" +%d more", len(sorted)-cap)
}

// strconvQuote renders a yaml-safe double-quoted scalar.
func strconvQuote(s string) string { return fmt.Sprintf("%q", s) }
