"""bat_demo_reject — generated by tuxgo batchpy from testdata/batch/BAT_DEMO_REJECT.pc.

Source batch: bat_demo_reject (entry main).
Shape: simple · DML loop: batch · transactions: DatabaseRouter context manager owns commit/rollback.
Template set: tuxgo py v1.
"""
import logging
from typing import Any, Dict, Iterator, List, Optional, Tuple

import oracledb

from core.db_router import DatabaseRouter, DbMode

logger = logging.getLogger("app.bat_demo_reject")

CHUNK_SIZE = 1000

# =====================================================================
# SQL Query Constants (source fidelity-gated via sqlchk)
# =====================================================================

SELECT_DEMO_TI_REJECT_QUERY = """
SELECT
    DEMO_TI_FORM_NO
FROM DEMO_TI_ORDERS
WHERE DEMO_TI_STATUS='A'
    AND (trunc(SYSDATE) - trunc(DEMO_TI_ORDER_DATE)) > 60
"""

UPDATE_DEMO_TI_REJECT_QUERY = """
UPDATE DEMO_TI_ORDERS
SET DEMO_TI_STATUS = 'X',
    DEMO_TI_REJ_REM = 'Demo rejection remark for the synthetic corpus',
    DEMO_TI_REJ_DATE = sysdate,
    DEMO_TI_STTS_CHG_DT = sysdate,
    DEMO_TI_UPDT_CNT = 1
WHERE DEMO_TI_FORM_NO = :sql_demo_ti_form_no
    AND DEMO_TI_STATUS = 'A'
"""

SELECT_DEMO_FOLIO_EXP_QUERY = """
SELECT
    a.dfc_match_acc,
    a.dfc_comp_cd,
    nvl(a.dfc_sch_cd, 'N'),
    a.DFC_SOURCE_FOLIO,
    a.DFC_TARGET_FOLIO
FROM demo_folio_rqst a
WHERE NOT EXISTS (SELECT 'x' FROM demo_folio_rqst_mkcrkr b WHERE a.DFC_MATCH_ACC=b.dfc_match_acc AND a.DFC_COMP_CD=b.dfc_comp_cd AND nvl(a.dfc_sch_cd,'N')=nvl(b.dfc_sch_cd,'N') AND a.DFC_SOURCE_FOLIO=b.DFC_SOURCE_FOLIO AND a.DFC_TARGET_FOLIO= b.DFC_TARGET_FOLIO AND a.DFC_PROCESS_FLAG = 'N')
    AND a.DFC_PROCESS_FLAG = 'N'
    AND (trunc(SYSDATE) - trunc(a.DFC_INSERT_DATE)) > 90
"""

UPDATE_DEMO_FOLIO_EXP_QUERY = """
UPDATE demo_folio_rqst
SET DFC_PROCESS_FLAG = 'X',
    DFC_UPDATE_DT = sysdate
WHERE DFC_MATCH_ACC = :sql_dfc_match_acc
    AND DFC_COMP_CD = :sql_dfc_comp_cd
    AND NVL(DFC_SCH_CD,'N') = :sql_dfc_sch_cd
    AND DFC_SOURCE_FOLIO = :sql_dfc_source_folio
    AND DFC_TARGET_FOLIO = :sql_dfc_target_folio
    AND DFC_PROCESS_FLAG = 'N'
"""

# =====================================================================
# Data Access Layer (pure cursor functions — mockable with a cursor double)
# =====================================================================

def fetch_demo_ti_reject(cursor: oracledb.Cursor) -> List[Tuple]:
    """Fetches the demo_ti_reject rows."""
    cursor.execute(SELECT_DEMO_TI_REJECT_QUERY)
    return cursor.fetchall()

def update_demo_ti_reject(cursor: oracledb.Cursor, records: List[Tuple]) -> int:
    """Executes UPDATE_DEMO_TI_REJECT_QUERY for the given rows."""
    cursor.executemany(UPDATE_DEMO_TI_REJECT_QUERY, [(r[0],) for r in records])
    return cursor.rowcount

def fetch_demo_folio_exp(cursor: oracledb.Cursor) -> List[Tuple]:
    """Fetches the demo_folio_exp rows."""
    cursor.execute(SELECT_DEMO_FOLIO_EXP_QUERY)
    return cursor.fetchall()

def update_demo_folio_exp(cursor: oracledb.Cursor, records: List[Tuple]) -> int:
    """Executes UPDATE_DEMO_FOLIO_EXP_QUERY for the given rows."""
    cursor.executemany(UPDATE_DEMO_FOLIO_EXP_QUERY, [(r[0], r[1], r[2], r[3], r[4]) for r in records])
    return cursor.rowcount

# =====================================================================
# Service Layer
# =====================================================================

class BatDemoRejectService:
    """bat_demo_reject — converted from testdata/batch/BAT_DEMO_REJECT.pc (BP rubric v1)."""

    def __init__(self, db_router: DatabaseRouter = None):
        # BP-5: the router context manager owns commit/rollback; DI keeps the
        # service unit-testable with a router double.
        self.db_router = db_router or DatabaseRouter()

    def process_demo_ti_reject_phase(self) -> int:
        """Phase 1: cursor demo_ti_reject → demo_ti_orders (batch DML)."""
        logger.info("Phase 1: fetching rows for cursor demo_ti_reject")
        with self.db_router.get_connection(mode=DbMode.READ) as conn:
            with conn.cursor() as cur:
                rows = fetch_demo_ti_reject(cur)
        if not rows:
            logger.info("No data found for demo_ti_reject")
            return 0
        logger.info("demo_ti_reject: %d rows to process", len(rows))
        total = 0
        with self.db_router.get_connection(mode=DbMode.WRITE) as conn:
            with conn.cursor() as cur:
                for i in range(0, len(rows), CHUNK_SIZE):
                    total += update_demo_ti_reject(cur, rows[i:i + CHUNK_SIZE])
                    logger.info("number of recs processed is %d", total)
        return total

    def process_demo_folio_exp_phase(self) -> int:
        """Phase 2: cursor demo_folio_exp → demo_folio_rqst (batch DML)."""
        logger.info("Phase 2: fetching rows for cursor demo_folio_exp")
        with self.db_router.get_connection(mode=DbMode.READ) as conn:
            with conn.cursor() as cur:
                rows = fetch_demo_folio_exp(cur)
        if not rows:
            logger.info("No data found for demo_folio_exp")
            return 0
        logger.info("demo_folio_exp: %d rows to process", len(rows))
        total = 0
        with self.db_router.get_connection(mode=DbMode.WRITE) as conn:
            with conn.cursor() as cur:
                for i in range(0, len(rows), CHUNK_SIZE):
                    total += update_demo_folio_exp(cur, rows[i:i + CHUNK_SIZE])
                    logger.info("number of recs processed is %d", total)
        return total

    def process_daily_batch(self, workers: int = 1) -> Dict[str, Any]:
        """Unified runner entry point orchestrating all phases."""
        logger.info("Invoking bat_demo_reject via unified runner with %d workers.", workers)
        logger.info("****** bat_demo_reject - starting ******")
        try:
            demo_ti_reject_records = self.process_demo_ti_reject_phase()
            demo_folio_exp_records = self.process_demo_folio_exp_phase()
            logger.info("****** bat_demo_reject - exiting ******")
            return {
                "status": "SUCCESS",
                "demo_ti_reject_records": demo_ti_reject_records,
                "demo_folio_exp_records": demo_folio_exp_records,
            }
        except Exception as ex:
            logger.error("Application error caught during batch sequence: %s", ex)
            raise
