"""bat_demo_returns — generated by tuxgo batchpy from testdata/batch/BAT_DEMO_RETURNS.pc.

Source batch: bat_demo_returns (entry main).
Shape: repo · DML loop: batch · transactions: DatabaseRouter context manager owns commit/rollback.
Template set: tuxgo py v1.
"""
import logging
from typing import Any, Dict, Iterator, List, Optional, Tuple

import oracledb

from core.db_router import DatabaseRouter, DbMode

logger = logging.getLogger("app.bat_demo_returns")

CHUNK_SIZE = 1000

# =====================================================================
# SQL Query Constants (source fidelity-gated via sqlchk)
# =====================================================================

TRUNCATE_DEMO_RET_TMP_QUERY = """
TRUNCATE TABLE DEMO_RET_TMP
"""

INSERT_DEMO_RET_TMP_QUERY = """
INSERT INTO DEMO_RET_TMP ( DEMO_RET_TMP_BSKT_ID, DEMO_RET_TMP_WEIGHT, DEMO_RET_TMP_RETURN, DEMO_RET_TMP_AMFI_CD ) ( SELECT MBM_DEMO_BSKT_ID, NVL(MBD_DEMO_WEIGHT,0), NVL(ROUND(DEMO_RET,2),0), DEMO_NAV_AMFI_CD FROM DEMO_RET_MSTR, DEMO_RET_DTL, DEMO_CONTENT@CONTENT_DB P2P WHERE MBM_DEMO_BSKT_ID = MBD_DEMO_BSKT_ID AND MBD_DEMO_ACTV_FLG = 'Y' AND P2P.DEMOCODE(+) = DEMO_NAV_AMFI_CD )
"""

FETCH_DEMO_RET_TMP_QUERY = """
SELECT DEMO_RET_TMP_BSKT_ID, DEMO_RET_TMP_WEIGHT, DEMO_RET_TMP_RETURN, DEMO_RET_TMP_AMFI_CD, ROWID FROM DEMO_RET_TMP WHERE DEMO_RET_TMP_PROCESS_FLG = 'N' AND ROWNUM<2 ORDER BY DEMO_RET_TMP_BSKT_ID
"""

FETCH_DUAL_QUERY = """
SELECT ROUND(:d_final,2) FROM DUAL
"""

UPDATE_DEMO_RET_MSTR_QUERY = """
UPDATE DEMO_RET_MSTR SET DEMO_MSTR_FINAL_RET = :d_final WHERE MBM_DEMO_BSKT_ID = :l_prev_bskt_id
"""

UPDATE_DEMO_RET_TMP_QUERY = """
UPDATE DEMO_RET_TMP SET DEMO_RET_TMP_PROCESS_FLG = 'Y' WHERE ROWID =:v_rowid
"""

# =====================================================================
# Repository (deterministic scaffold — BP-3)
# =====================================================================

class BatDemoReturnsRepository:
    """Encapsulates all database operations for bat_demo_returns."""

    def __init__(self, db_router: DatabaseRouter):
        self.db_router = db_router

    def rebuild_demo_ret_tmp(self) -> int:
        """Rebuilds the staging table (truncate + insert)."""
        with self.db_router.get_connection(mode=DbMode.WRITE) as conn:
            with conn.cursor() as cur:
                cur.execute(TRUNCATE_DEMO_RET_TMP_QUERY)
                cur.execute(INSERT_DEMO_RET_TMP_QUERY)
                return cur.rowcount

    def fetch_demo_ret_tmp(self, sql_demo_ret_tmp_bskt_id: Any, sql_demo_ret_tmp_weight: Any, sql_demo_ret_tmp_return: Any, sql_demo_ret_tmp_amfi_cd: Any, v_rowid: Any) -> Optional[Tuple]:
        """Fetches rows (READ mode)."""
        with self.db_router.get_connection(mode=DbMode.READ) as conn:
            with conn.cursor() as cur:
                cur.execute(FETCH_DEMO_RET_TMP_QUERY, {"sql_demo_ret_tmp_bskt_id": sql_demo_ret_tmp_bskt_id, "sql_demo_ret_tmp_weight": sql_demo_ret_tmp_weight, "sql_demo_ret_tmp_return": sql_demo_ret_tmp_return, "sql_demo_ret_tmp_amfi_cd": sql_demo_ret_tmp_amfi_cd, "v_rowid": v_rowid})
                return cur.fetchone()

    def fetch_dual(self, d_final: Any) -> Optional[Tuple]:
        """Fetches rows (READ mode)."""
        with self.db_router.get_connection(mode=DbMode.READ) as conn:
            with conn.cursor() as cur:
                cur.execute(FETCH_DUAL_QUERY, {"d_final": d_final})
                return cur.fetchone()

    def update_demo_ret_mstr(self, d_final: Any, l_prev_bskt_id: Any) -> int:
        """Executes the DML (WRITE mode)."""
        with self.db_router.get_connection(mode=DbMode.WRITE) as conn:
            with conn.cursor() as cur:
                cur.execute(UPDATE_DEMO_RET_MSTR_QUERY, {"d_final": d_final, "l_prev_bskt_id": l_prev_bskt_id})
                return cur.rowcount

    def update_demo_ret_tmp(self, v_rowid: Any) -> int:
        """Executes the DML (WRITE mode)."""
        with self.db_router.get_connection(mode=DbMode.WRITE) as conn:
            with conn.cursor() as cur:
                cur.execute(UPDATE_DEMO_RET_TMP_QUERY, {"v_rowid": v_rowid})
                return cur.rowcount


class BatDemoReturnsService:
    """bat_demo_returns — converted from testdata/batch/BAT_DEMO_RETURNS.pc (BP rubric v1)."""

    def __init__(self, repo: Optional[BatDemoReturnsRepository] = None, db_router: Optional[DatabaseRouter] = None):
        # BP-5: the router context manager owns commit/rollback; DI keeps the
        # service unit-testable.
        self.db_router = db_router or DatabaseRouter()
        self.repo = repo or BatDemoReturnsRepository(self.db_router)

    def process_daily_batch(self, workers: int = 1) -> Dict[str, Any]:
        """Unified runner entry point orchestrating all phases."""
        # tuxgo:TODO service body — pending LLM fill (BP-6; -no-llm run)
        raise NotImplementedError("batchpy: service body pending LLM fill")
